### ISSUE TITLE
Can't connect to CliclHouse from local minikube

### ISSUE THREAD

**Issue by vladislav-bakanov** [ClickHouse/clickhouse-kafka-connect#377]
### Describe the bug
Hi! Discovered bug very similar as [this issue](https://github.com/ClickHouse/clickhouse-java/issues/1444) with JDBC driver, but with this driver plugin.

1. I deployed Kafka Connect Strimzi CRD on local k8 cluster (minikube). I successfully connected to my company Kafka deployed on test environment.
1. I built docker image, based on: `quay.io/strimzi/kafka:0.39.0-kafka-3.5.0`
1. I added Strimzi Kafka Connector CRD on local k8s cluster (minikube). I see in logs, that this connector was successfully consumed by Kafka Connect service and I can see this connector on 

### Steps to reproduce
1. Deploy Strimzi Kafka Opearator v.0.39.0 in minikube
2. Deploy Strimzi Kafka resource in minikube
3. Deploy Strimzi Kafka Connect resource (with docker image with installed clickhouse-kafka-connect plugin) in minikube
4. Deploy Strimzi Kafka Connector resource

### Expected behaviour
Connector successfully connects to the Clickhouse server and starts streaming.

### Error log
```
java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: The target server failed to respond, server ClickHouseNode [uri=http://XXXXXXXXXXXXXXXXXXXX.europe-west4.gcp.clickhouse.cloud:8443/XXXXXXXXXXXXXXXXXXXX]
```

#### Environment
* Kafka cluster operator (Strimzi CRD): 0.39.0
* Kafka version: 3.5.0
* Clickhouse Kafka Connect version: 1.0.16
* Minikube version: v1.32.0 [commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d]
* OS: MacOS [M2]

#### ClickHouse server
* ClickHouse Server version: ClickHouse 24.1 [Cloud]

#### Kafka Connector configuration:
```
apiVersion: [kafka.strimzi.io/v1beta2](http://kafka.strimzi.io/v1beta2)
kind: KafkaConnector
metadata:
  name: XXXXXXXXXXXX-kafka-connector
  namespace: kafka
  labels:
    [strimzi.io/cluster](http://strimzi.io/cluster): XXXXXXXXXXXX-kafkaconnect
spec:
  class: com.clickhouse.kafka.connect.ClickHouseSinkConnector
  tasksMax: 1
  autoRestart:
    enabled: true
  state: running
  config:
    topics: XXXXXXXXXXXXXXXXXXXX
    topic2TableMap: "XXXXXXXXXXXXXXXXXXXX=my_clickhouse_table"

    hostname: [XXXXXXXXXXXXXXXXXXXX.europe-west4.gcp.clickhouse.cloud](http://xxxxxxxxxxxxxxxxxxxx.europe-west4.gcp.clickhouse.cloud/)
    port: "8443"
    database: XXXXXXXXXXXXXXXXXXXX
    username: XXXXXXXXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXXXXXXXX
    sslEnable: "true"
    security.protocol: SSL

    suppressTableExistenceException: "false"

    key.deserializer: io.confluent.connect.avro.AvroConverter
    value.deserializer: io.confluent.connect.avro.AvroConverter

    # Schema
    schema.registry.url: http://xxxxxxxxxxxxxxxxxxxx.com/
    value.converter.schemas.enable: "true"
    value.converter.schema.registry.url: http://xxxxxxxxxxxxxxxxxxxx.com/
    key.converter.schema.registry.url: http://xxxxxxxxxxxxxxxxxxxx.com/

    # Transforms
    transforms: flatten
    transforms.flatten.type: org.apache.kafka.connect.transforms.Flatten$Value
    transforms.flatten.delimiter: "."
```

#### Kafka Connect configuration:
```
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: XXXXXXXXXXXXXXXX
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: docker-image-strimzi-kafka-connect-with-clickhouse:0.1.0-dev.1
  replicas: 1
  authentication:
    type: scram-sha-512
    username: kafka-user-dwh
    passwordSecret:
      secretName: kafka-password
      password: password

  bootstrapServers: my-kafka.com:9094
  config:
    group.id: dwh-kafka-connect
    offset.storage.topic: uat.dwh.kafka-connect.offsets
    config.storage.topic: uat.dwh.kafka-connect.configs
    status.storage.topic: uat.dwh.kafka-connect.status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    
  # Logging
  logging:
    type: inline
    loggers:
      log4j.rootLogger: INFO
      log4j.logger.org.eclipse.jetty.http: TRACE
      log4j.logger.org.apache.kafka.connect: TRACE
      log4j.logger.com.clickhouse.kafka.connect: TRACE
```

#### Docker image:
```
FROM quay.io/strimzi/kafka:0.39.0-kafka-3.5.0

USER root:root
# COPY ./clickhouse-kafka-connect-v1.0.17.jar /opt/kafka/plugins/
COPY ./clickhouse-kafka-connect-v1.0.16.jar /opt/kafka/plugins/

USER 1001
```
