### ISSUE TITLE
kafka connect sink can not process with empty array 

### ISSUE THREAD

**Issue by phongbui81062** [ClickHouse/clickhouse-kafka-connect#457]
### Describe the bug
Hi everyone,

I have this case and I don't know what is the problem.

I create kafka connect sink, which reads data from CDC (Postgres) with Avro format. However when I try to sink data to Table which contains Array(String) columns (it worked well with Array(UInt32)), the error SIZES_OF_ARRAYS_DONT_MATCH, seem like ClickHouse tried to compare the length of array columns
### Steps to reproduce
1. Create table 
``` 
CREATE OR REPLACE TABLE db.`topic_name`
(
    `before.id` Nullable(UInt32),
    `before.name` Nullable(String),
    `before.slug_name` Nullable(String),
    `before.aftership_id`              Array(String),
    `before.carrier_17_id`             Array(String),
    `before.carrier_cs_phone` Nullable(String),
    `before.carrier_id` Nullable(String),
    `before.carrier_language` Nullable(String),
    `before.carrier_logo` Nullable(String),
    `before.carrier_support_languages` Array(String),
    `before.carrier_url` Nullable(String),
    `before.carrier_url_tracking` Nullable(String),
    `before.comments` Nullable(String),
    `before.carrier_countries_iso`     Array(String),
    `before.pattern_regex`             Array(String),
    `before.scraper_id` Nullable(UInt32),
    `before.base_weight` Nullable(DOUBLE),
    `before.cms_url` Nullable(String),
    `before.allowed_concurrent_request_count` Nullable(UInt32),
    `before.postal_scrape` Nullable(Bool),
    `before.carrier_countries`         Array(String),
    `before.updated_date` Nullable(DateTime64(6)),
    `before.is_hidden` Nullable(Bool),
    `before.merchant_parameters` Nullable(String),
    `before.last_calc_rating` Nullable(DateTime64(6)),
    `before.rating` Nullable(String),
    `after.id` Nullable(UInt32),
    `after.name` Nullable(String),
    `after.slug_name` Nullable(String),
    `after.aftership_id`               Array(String),
    `after.carrier_17_id`              Array(String),
    `after.carrier_cs_phone` Nullable(String),
    `after.carrier_id` Nullable(String),
    `after.carrier_language` Nullable(String),
    `after.carrier_logo` Nullable(String),
    `after.carrier_support_languages`  Array(String) CODEC (ZSTD),
    `after.carrier_url` Nullable(String),
    `after.carrier_url_tracking` Nullable(String),
    `after.comments` Nullable(String),
    `after.carrier_countries_iso`      Array(String),
    `after.pattern_regex`              Array(String),
    `after.scraper_id` Nullable(UInt32),
    `after.base_weight` Nullable(DOUBLE),
    `after.cms_url` Nullable(String),
    `after.allowed_concurrent_request_count` Nullable(UInt32),
    `after.postal_scrape` Nullable(Bool),
    `after.carrier_countries`          Array(String),
    `after.updated_date` Nullable(DateTime64(6)),
    `after.is_hidden` Nullable(Bool),
    `after.merchant_parameters` Nullable(String),
    `after.last_calc_rating` Nullable(DateTime64(6)),
    `after.rating` Nullable(String),
    ts_ms                              Int64 CODEC (LZ4),
    source_table                       Nullable(String),
    op                                 LowCardinality(String) CODEC (ZSTD)
)
    ENGINE MergeTree
        ORDER BY tuple();
```
2. Kafka connect configuration:
```
name: config-name
  credentialsName: ch-credential
  tasksMax: 1
  config:
    topics: topic_name
    ssl: false
    security.protocol: SASL_PLAINTEXT
    behavior.on.null.values: ignore
    behavior.on.error: ignore
    database: db_name
    hostname: db_host
    port: 8123
    transforms: flatten
    transforms.flatten.type: org.apache.kafka.connect.transforms.Flatten$Value
    transforms.flatten.delimiter: .
    value.converter: io.confluent.connect.avro.AvroConverter
    key.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: schema-registry:8081
    key.converter.schema.registry.url: schema-registry:8081
    value.converter.schemas.enable: true
    exactlyOnce: true
    errors.log.enable: true
    errors.log.include.messages: true
    schemas.enable: false
    RowBinaryWithDefaults: true
```
3. Trigger WAL
```
{
  "before": {
    "topic_name.Value": {
      "aftership_id": {
        "array": []
      },
      "carrier_17_id": {
        "array": [
          {
            "string": "190015"
          }
        ]
      }
    }
  },
  "op": "u",
  "transaction": null,
  "ts_ms": {
    "long": 1727944418823
  }
}
```
Can you help me to resolve this problems?
